Minor changes to membership - current error "java.lang.NoSuchMethodError: Mijdas.RoadApp.spring.Controllers.DatabaseControllers.SQLDatabase.executeProcedure(LMijdas/RoadApp/spring/Controllers/DatabaseControllers/MijdasDB$Procedure;Ljava/lang/String;)Ljava/sql/ResultSet;"